add  the back end for requestList
TalaatHarb/invoice-tracker pull request #28
Opened 2022-08-23 17:35 UTC by khaledHarb1313

2022-08-24 09:58 UTC, mzakariia commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/services/RequestLeaveServices.java
> +	public Request update_a_leave_request(int requestId, Request request) {
add checks if these fields are empty or not. Simply adding what is sent may remove existing data.

2022-08-24 10:01 UTC, mzakariia commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/services/RequestLeaveServices.java
> +			body.setUserArabicName(user.getArabicName());
missing fields from requests that may be important for the HR/Manager/employee to see such as status and reviewed by fields

2022-08-24 10:02 UTC, mzakariia commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/controllers/RequestController.java
> +@RequestMapping("/Requests")
Make request mapping /api/requests instead of only requests to match other controllers

2022-08-24 10:04 UTC, mzakariia commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/services/RequestLeaveServices.java
> +		requestFromDB.setEndDate(request.getEndDate());
add checks if these fields are empty or not. Simply adding what is sent may remove existing data. and use @Transactional annotation

2022-08-24 10:05 UTC, mzakariia requested changes
subtle changes need to be made

2022-08-24 11:11 UTC, khaledHarb1313 commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/services/RequestLeaveServices.java
> +			body.setUserArabicName(user.getArabicName());
in the user story there is non of them

2022-08-24 11:25 UTC, khaledHarb1313 commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/controllers/RequestController.java
> +@RequestMapping("/Requests")
done !

2022-08-24 11:58 UTC, AhmedElsayed200 commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/controllers/RequestController.java
> +@RequestMapping("/api/Requests")
There is a controller named "[AbsenceController.java]" already in the develop branch. It would be better if all the absence requests related to the user be in the same controller file.

2022-08-24 11:59 UTC, AhmedElsayed200 commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/repositories/RequestRepo.java
> +public interface RequestRepo extends JpaRepository<Request	, Integer>{
There is already "[RequestRepository.java]" in the develop branch. It would be better if you delete this file.

2022-08-24 12:02 UTC, AhmedElsayed200 commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/services/RequestLeaveServices.java
> +public class RequestLeaveServices {
AbsenceService.java already exists in the develop branch. I would recommend merging all the new lines to the already existing file.

2022-08-24 13:19 UTC, khaledHarb1313 commented on invoice-tracker-backend/src/main/java/net/talaatharb/invoicetracker/controllers/RequestController.java
> +@RequestMapping("/api/Requests")
done

2022-08-24 13:29 UTC, khaledHarb1313 commented
some changes added and approved before it submit

2022-08-24 15:02 UTC, AhmedElsayed200 approved these changes

2022-08-24 15:13 UTC, Abdelrhman-Samir-99 approved these changes
Just intend your code if possible, great job!

2022-08-24 20:15 UTC, Elrashede approved these changes

2022-08-25 00:14 UTC, mzakariia approved these changes

2022-08-25 06:21 UTC, merged